exclude: 'tests/__snapshots__/.*ambr'  # syrupy snapshots
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [ "--select", "I", "--fix" ]
      - id: ruff-format
#   - repo: https://github.com/asottile/reorder-python-imports
#     rev: v3.13.0
#     hooks:
#       - id: reorder-python-imports
