[adtl]
name = "example"
description = "example"
returnUnmatched = true
defs = { "Y/N/NK" = { caseInsensitive = true, values = { non = false, oui = true } } }

[adtl.tables]
animals = { kind = "oneToOne", schema = "../../../tests/test_autoparser/schemas/animals.schema.json" }

[animals]
age_months = { field = "AgeMois         ", description = "Age in Months" }
age_years = { field = "AgeAns", description = "Age in Years" }
chipped = { field = "Micropucé", description = "Microchipped", ref = "Y/N/NK" }
date_of_death = { field = "DateDec", description = "Date of Death" }
identity = { field = "Identité", description = "Identity" }
name = { field = "Nom complet ", description = "Full Name" }
notification_date = { field = "DateNotification", description = "Notification Date" }
pet = { field = "AnimalDeCompagnie", description = "Pet Animal", ref = "Y/N/NK" }
country_iso3 = ""

[animals.case_status]
field = "StatusCas"
description = "Case Status"
values = { "décédé" = "dead", vivant = "alive" }
caseInsensitive = true

[animals.classification]
field = "Classicfication "
description = "Classification"
caseInsensitive = true

[animals.classification.values]
rept = "reptile"
fish = "fish"
amphibie = "amphibian"
"mammifère" = "mammal"
poisson = "fish"
oiseau = "bird"

[animals.loc_admin_1]
field = "Province"
description = "Province"
values = { equateur = "", katanga = "", orientale = "" }
caseInsensitive = true

[animals.sex]
field = "Sexe"
description = "Gender"
values = { f = "female", m = "male" }
caseInsensitive = true

[animals.underlying_conditions]
field = "ConditionsPreexistantes"
description = "Preexisting Conditions"
caseInsensitive = true
type = "enum_list"

[animals.underlying_conditions.values]
"diabète" = "diabetes"
convulsions = "seizures"
"problèmes d'échelle" = "skin problems"
vomir = "vomiting"
arthrite = "arthritis"
