[adtl]
name = "example"
description = "example"
returnUnmatched = true
defs = { "Y/N/NK" = { caseInsensitive = true, values = { non = false, oui = true } } }

[adtl.tables]
animals = { kind = "oneToOne", schema = "../../../tests/test_autoparser/schemas/animals.schema.json" }

[animals]
age_months = { field = "AgeMois         ", description = "Age (Months)" }
age_years = { field = "AgeAns", description = "Age (Years)" }
chipped = { field = "Micropucé", description = "Microchipped", ref = "Y/N/NK" }
date_of_death = { field = "DateDec", description = "Date of Death" }
identity = { field = "Identité", description = "Identity" }
name = { field = "Nom complet ", description = "Full Name" }
notification_date = { field = "DateNotification", description = "Notification Date" }
pet = { field = "AnimalDeCompagnie", description = "Pet", ref = "Y/N/NK" }
country_iso3 = ""

[animals.case_status]
field = "StatusCas"
description = "Case Status"
values = { vivant = "alive", "décédé" = "dead" }
caseInsensitive = true

[animals.classification]
field = "Classicfication "
description = "Classification"
caseInsensitive = true

[animals.classification.values]
amphibie = "amphibian"
fish = "fish"
oiseau = "bird"
rept = "reptile"
poisson = "fish"
"mammifère" = "mammal"

[animals.loc_admin_1]
field = "Province"
description = "Province"
values = { equateur = "", katanga = "", orientale = "" }
caseInsensitive = true

[animals.sex]
field = "Sexe"
description = "Sex"
values = { f = "female", m = "male" }
caseInsensitive = true

[animals.underlying_conditions]
field = "ConditionsPreexistantes"
description = "Pre-existing Conditions"
caseInsensitive = true
type = "enum_list"

[animals.underlying_conditions.values]
convulsions = "seizures"
"problèmes d'échelle" = "skin problems"
vomir = "vomiting"
"diabète" = "diabetes"
arthrite = "arthritis"
