[adtl]
name = "example"
description = "example"
returnUnmatched = true
defs = { "Y/N/NK" = { caseInsensitive = true, values = { oui = true, non = false } } }

[adtl.tables]
animals = { kind = "oneToOne", schema = "../../../tests/test_autoparser/schemas/animals.schema.json" }

[animals]
age_months = { field = "AgeMois         ", description = "Age (Months)" }
age_years = { field = "AgeAns", description = "Age (Years)" }
chipped = { field = "Micropucé", description = "Microchipped", ref = "Y/N/NK" }
date_of_death = { field = "DateDec", description = "Died Date" }
identity = { field = "Identité", description = "Identity" }
name = { field = "Nom complet ", description = "Full Name" }
notification_date = { field = "DateNotification", description = "Notification Date" }
pet = { field = "AnimalDeCompagnie", description = "Pet Animal", ref = "Y/N/NK" }
country_iso3 = ""

[animals.case_status]
field = "StatusCas"
description = "Case Status"
values = { vivant = "alive", "décédé" = "dead" }
caseInsensitive = true

[animals.classification]
field = "Classicfication "
description = "Classification"
caseInsensitive = true

[animals.classification.values]
poisson = "fish"
oiseau = "bird"
amphibie = "amphibian"
rept = "reptile"
"mammifère" = "mammal"
fish = "invertebrate"

[animals.loc_admin_1]
field = "Province"
description = "Province"
values = { equateur = "", katanga = "", orientale = "" }
caseInsensitive = true

[animals.sex]
field = "Sexe"
description = "Sex"
values = { m = "male", f = "female" }
caseInsensitive = true

[animals.underlying_conditions]
field = "ConditionsPreexistantes"
description = "Preexisting Conditions"
caseInsensitive = true
type = "enum_list"

[animals.underlying_conditions.values]
"problèmes d'échelle" = "skin problems"
convulsions = "seizures"
"diabète" = "diabetes"
vomir = "vomiting"
arthrite = "arthritis"
